apiVersion: v1
kind: ConfigMap
metadata:
  name: rautazap-config
data:
  # Configurações existentes
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/rautazap"
  SPRING_DATA_REDIS_HOST: "redis-master"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.default.svc.cluster.local:9092"

  # Chaves atualizadas para o chart do ActiveMQ da Bitnami
  BROKER_HOST: "artemis-service"
  BROKER_PORT: "61613" # Porta STOMP do ActiveMQ
  BROKER_USERNAME: "artemis" # Usuário padrão do chart da Bitnami
  BROKER_PASSWORD: "rautazap" # Senha definida no comando helm install

  # Chave para tornar a inicialização do Kafka mais resiliente
  SPRING_KAFKA_ADMIN_FAIL_FAST: "false"

  # Adicionado para expor os endpoints de saúde do Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health"