apiVersion: v1
kind: ConfigMap
metadata:
  name: rautazap-config
data:
  # Configurações existentes
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/rautazap"
  SPRING_DATA_REDIS_HOST: "redis-master"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka:9092"

  # Novas chaves para o Artemis, lidas pelo WebSocketConfig.java
  # O Spring Boot mapeia ARTEMIS_RELAY_HOST para artemis.relay.host
  ARTEMIS_RELAY_HOST: "artemis-activemq-artemis"
  ARTEMIS_RELAY_PORT: "61613" # Porta STOMP do Artemis
  ARTEMIS_USER: "artemis" # Usuário padrão do chart
  ARTEMIS_PASSWORD: "artemis" # Senha padrão do chart (artemis ao contrário)

  # Chave para tornar a inicialização do Kafka mais resiliente
  SPRING_KAFKA_ADMIN_FAIL_FAST: "false"

  # Adicionado para expor os endpoints de saúde do Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health"