apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-servicemonitor
  labels:
    # CORREÇÃO: A label deve corresponder exatamente à que o Prometheus procura.
    Release: prometheus
spec:
  selector:
    matchLabels:
      # Procura por serviços com estas labels (criadas pelo chart do Kafka)
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka-exporter
  endpoints:
    - port: http-metrics
      interval: 15s