apiVersion: v1
kind: Service
metadata:
  name: rautazap-service
spec:
  type: LoadBalancer
  selector:
    app: rautazap
  ports:
    - protocol: TCP
      port: 8080       # Porta externa
      targetPort: 8080 # Porta do container